/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db;


import ee.ttu.unomomento.db.tables.Degree;
import ee.ttu.unomomento.db.tables.Faculty;
import ee.ttu.unomomento.db.tables.Person;
import ee.ttu.unomomento.db.tables.PersonFaculty;
import ee.ttu.unomomento.db.tables.PersonRole;
import ee.ttu.unomomento.db.tables.PersonState;
import ee.ttu.unomomento.db.tables.Role;
import ee.ttu.unomomento.db.tables.Thesis;
import ee.ttu.unomomento.db.tables.ThesisCandidate;
import ee.ttu.unomomento.db.tables.ThesisOwner;
import ee.ttu.unomomento.db.tables.ThesisState;
import ee.ttu.unomomento.db.tables.ThesisTag;
import ee.ttu.unomomento.db.tables.records.DegreeRecord;
import ee.ttu.unomomento.db.tables.records.FacultyRecord;
import ee.ttu.unomomento.db.tables.records.PersonFacultyRecord;
import ee.ttu.unomomento.db.tables.records.PersonRecord;
import ee.ttu.unomomento.db.tables.records.PersonRoleRecord;
import ee.ttu.unomomento.db.tables.records.PersonStateRecord;
import ee.ttu.unomomento.db.tables.records.RoleRecord;
import ee.ttu.unomomento.db.tables.records.ThesisCandidateRecord;
import ee.ttu.unomomento.db.tables.records.ThesisOwnerRecord;
import ee.ttu.unomomento.db.tables.records.ThesisRecord;
import ee.ttu.unomomento.db.tables.records.ThesisStateRecord;
import ee.ttu.unomomento.db.tables.records.ThesisTagRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PersonRecord, Long> IDENTITY_PERSON = Identities0.IDENTITY_PERSON;
    public static final Identity<ThesisRecord, Long> IDENTITY_THESIS = Identities0.IDENTITY_THESIS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DegreeRecord> PK_DEGREE_DEGREE_CODE = UniqueKeys0.PK_DEGREE_DEGREE_CODE;
    public static final UniqueKey<DegreeRecord> AK_DEGREE_EE_NAME = UniqueKeys0.AK_DEGREE_EE_NAME;
    public static final UniqueKey<DegreeRecord> AK_DEGREE_EN_NAME = UniqueKeys0.AK_DEGREE_EN_NAME;
    public static final UniqueKey<FacultyRecord> PK_FACULTY_FACULTY_CODE = UniqueKeys0.PK_FACULTY_FACULTY_CODE;
    public static final UniqueKey<FacultyRecord> AK_FACULTY_EE_NAME = UniqueKeys0.AK_FACULTY_EE_NAME;
    public static final UniqueKey<FacultyRecord> AK_FACULTY_EN_NAME = UniqueKeys0.AK_FACULTY_EN_NAME;
    public static final UniqueKey<PersonRecord> PK_PERSON_PERSON_ID = UniqueKeys0.PK_PERSON_PERSON_ID;
    public static final UniqueKey<PersonRecord> AK_PERSON_UNI_ID = UniqueKeys0.AK_PERSON_UNI_ID;
    public static final UniqueKey<PersonFacultyRecord> PK_PERSON_FACULTY_PERSON_ID_FACULTY_CODE = UniqueKeys0.PK_PERSON_FACULTY_PERSON_ID_FACULTY_CODE;
    public static final UniqueKey<PersonRoleRecord> PK_PERSON_ROLE_PERSON_ID_ROLE_CODE = UniqueKeys0.PK_PERSON_ROLE_PERSON_ID_ROLE_CODE;
    public static final UniqueKey<PersonStateRecord> PK_PERSON_STATE_PERSON_STATE_CODE = UniqueKeys0.PK_PERSON_STATE_PERSON_STATE_CODE;
    public static final UniqueKey<PersonStateRecord> AK_PERSON_STATE_EE_NAME = UniqueKeys0.AK_PERSON_STATE_EE_NAME;
    public static final UniqueKey<PersonStateRecord> AK_PERSON_STATE_EN_NAME = UniqueKeys0.AK_PERSON_STATE_EN_NAME;
    public static final UniqueKey<RoleRecord> PK_ROLE_PERSON_ROLE_CODE = UniqueKeys0.PK_ROLE_PERSON_ROLE_CODE;
    public static final UniqueKey<RoleRecord> AK_ROLE_EN_NAME = UniqueKeys0.AK_ROLE_EN_NAME;
    public static final UniqueKey<RoleRecord> AK_ROLE_EE_NAME = UniqueKeys0.AK_ROLE_EE_NAME;
    public static final UniqueKey<ThesisRecord> PK_THESIS_THESIS_ID = UniqueKeys0.PK_THESIS_THESIS_ID;
    public static final UniqueKey<ThesisCandidateRecord> PK_THESIS_CANDIDATE_THESIS_ID_CANDIDATE_ID = UniqueKeys0.PK_THESIS_CANDIDATE_THESIS_ID_CANDIDATE_ID;
    public static final UniqueKey<ThesisOwnerRecord> PK_THESIS_OWNER_THESIS_ID_PERSON_ID = UniqueKeys0.PK_THESIS_OWNER_THESIS_ID_PERSON_ID;
    public static final UniqueKey<ThesisStateRecord> PK_THESIS_STATE_THESIS_STATE_CODE = UniqueKeys0.PK_THESIS_STATE_THESIS_STATE_CODE;
    public static final UniqueKey<ThesisStateRecord> AK_THESIS_STATE_EE_NAME = UniqueKeys0.AK_THESIS_STATE_EE_NAME;
    public static final UniqueKey<ThesisStateRecord> AK_THESIS_STATE_EN_NAME = UniqueKeys0.AK_THESIS_STATE_EN_NAME;
    public static final UniqueKey<ThesisTagRecord> PK_THESIS_TAG_THESIS_ID_TAG_NAME = UniqueKeys0.PK_THESIS_TAG_THESIS_ID_TAG_NAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PersonRecord, DegreeRecord> PERSON__FK_PERSON_DEGREE_CODE = ForeignKeys0.PERSON__FK_PERSON_DEGREE_CODE;
    public static final ForeignKey<PersonRecord, PersonStateRecord> PERSON__FK_PERSON_PERSON_STATE_CODE = ForeignKeys0.PERSON__FK_PERSON_PERSON_STATE_CODE;
    public static final ForeignKey<PersonFacultyRecord, PersonRecord> PERSON_FACULTY__FK_PERSON_FACULTY_PERSON_ID = ForeignKeys0.PERSON_FACULTY__FK_PERSON_FACULTY_PERSON_ID;
    public static final ForeignKey<PersonFacultyRecord, FacultyRecord> PERSON_FACULTY__FK_PERSON_FACULTY_FACULTY_CODE = ForeignKeys0.PERSON_FACULTY__FK_PERSON_FACULTY_FACULTY_CODE;
    public static final ForeignKey<PersonRoleRecord, PersonRecord> PERSON_ROLE__FK_PERSON_ROLE_PERSON_ID = ForeignKeys0.PERSON_ROLE__FK_PERSON_ROLE_PERSON_ID;
    public static final ForeignKey<PersonRoleRecord, RoleRecord> PERSON_ROLE__FK_PERSON_ROLE_ROLE_CODE = ForeignKeys0.PERSON_ROLE__FK_PERSON_ROLE_ROLE_CODE;
    public static final ForeignKey<ThesisRecord, FacultyRecord> THESIS__FK_THESIS_FACULTY_CODE = ForeignKeys0.THESIS__FK_THESIS_FACULTY_CODE;
    public static final ForeignKey<ThesisRecord, ThesisStateRecord> THESIS__FK_THESIS_THESIS_STATE_CODE = ForeignKeys0.THESIS__FK_THESIS_THESIS_STATE_CODE;
    public static final ForeignKey<ThesisCandidateRecord, ThesisRecord> THESIS_CANDIDATE__FK_THESIS_CANDIDATE_THESIS_ID = ForeignKeys0.THESIS_CANDIDATE__FK_THESIS_CANDIDATE_THESIS_ID;
    public static final ForeignKey<ThesisCandidateRecord, PersonRecord> THESIS_CANDIDATE__FK_THESIS_CANDIDATE_CANDIDATE_ID = ForeignKeys0.THESIS_CANDIDATE__FK_THESIS_CANDIDATE_CANDIDATE_ID;
    public static final ForeignKey<ThesisOwnerRecord, ThesisRecord> THESIS_OWNER__FK_THESIS_OWNER_THESIS_ID = ForeignKeys0.THESIS_OWNER__FK_THESIS_OWNER_THESIS_ID;
    public static final ForeignKey<ThesisOwnerRecord, PersonRecord> THESIS_OWNER__FK_THESIS_OWNER_PERSON_ID = ForeignKeys0.THESIS_OWNER__FK_THESIS_OWNER_PERSON_ID;
    public static final ForeignKey<ThesisOwnerRecord, RoleRecord> THESIS_OWNER__FK_THESIS_OWNER_ROLE_CODE = ForeignKeys0.THESIS_OWNER__FK_THESIS_OWNER_ROLE_CODE;
    public static final ForeignKey<ThesisTagRecord, ThesisRecord> THESIS_TAG__FK_THESIS_TAG_THESIS_ID = ForeignKeys0.THESIS_TAG__FK_THESIS_TAG_THESIS_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PersonRecord, Long> IDENTITY_PERSON = createIdentity(Person.PERSON, Person.PERSON.PERSON_ID);
        public static Identity<ThesisRecord, Long> IDENTITY_THESIS = createIdentity(Thesis.THESIS, Thesis.THESIS.THESIS_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DegreeRecord> PK_DEGREE_DEGREE_CODE = createUniqueKey(Degree.DEGREE, "pk_degree_degree_code", Degree.DEGREE.DEGREE_CODE);
        public static final UniqueKey<DegreeRecord> AK_DEGREE_EE_NAME = createUniqueKey(Degree.DEGREE, "ak_degree_ee_name", Degree.DEGREE.EE_NAME);
        public static final UniqueKey<DegreeRecord> AK_DEGREE_EN_NAME = createUniqueKey(Degree.DEGREE, "ak_degree_en_name", Degree.DEGREE.EN_NAME);
        public static final UniqueKey<FacultyRecord> PK_FACULTY_FACULTY_CODE = createUniqueKey(Faculty.FACULTY, "pk_faculty_faculty_code", Faculty.FACULTY.FACULTY_CODE);
        public static final UniqueKey<FacultyRecord> AK_FACULTY_EE_NAME = createUniqueKey(Faculty.FACULTY, "ak_faculty_ee_name", Faculty.FACULTY.EE_NAME);
        public static final UniqueKey<FacultyRecord> AK_FACULTY_EN_NAME = createUniqueKey(Faculty.FACULTY, "ak_faculty_en_name", Faculty.FACULTY.EN_NAME);
        public static final UniqueKey<PersonRecord> PK_PERSON_PERSON_ID = createUniqueKey(Person.PERSON, "pk_person_person_id", Person.PERSON.PERSON_ID);
        public static final UniqueKey<PersonRecord> AK_PERSON_UNI_ID = createUniqueKey(Person.PERSON, "ak_person_uni_id", Person.PERSON.UNI_ID);
        public static final UniqueKey<PersonFacultyRecord> PK_PERSON_FACULTY_PERSON_ID_FACULTY_CODE = createUniqueKey(PersonFaculty.PERSON_FACULTY, "pk_person_faculty_person_id_faculty_code", PersonFaculty.PERSON_FACULTY.PERSON_ID, PersonFaculty.PERSON_FACULTY.FACULTY_CODE);
        public static final UniqueKey<PersonRoleRecord> PK_PERSON_ROLE_PERSON_ID_ROLE_CODE = createUniqueKey(PersonRole.PERSON_ROLE, "pk_person_role_person_id_role_code", PersonRole.PERSON_ROLE.PERSON_ID, PersonRole.PERSON_ROLE.ROLE_CODE);
        public static final UniqueKey<PersonStateRecord> PK_PERSON_STATE_PERSON_STATE_CODE = createUniqueKey(PersonState.PERSON_STATE, "pk_person_state_person_state_code", PersonState.PERSON_STATE.PERSON_STATE_CODE);
        public static final UniqueKey<PersonStateRecord> AK_PERSON_STATE_EE_NAME = createUniqueKey(PersonState.PERSON_STATE, "ak_person_state_ee_name", PersonState.PERSON_STATE.EE_NAME);
        public static final UniqueKey<PersonStateRecord> AK_PERSON_STATE_EN_NAME = createUniqueKey(PersonState.PERSON_STATE, "ak_person_state_en_name", PersonState.PERSON_STATE.EN_NAME);
        public static final UniqueKey<RoleRecord> PK_ROLE_PERSON_ROLE_CODE = createUniqueKey(Role.ROLE, "pk_role_person_role_code", Role.ROLE.ROLE_CODE);
        public static final UniqueKey<RoleRecord> AK_ROLE_EN_NAME = createUniqueKey(Role.ROLE, "ak_role_en_name", Role.ROLE.EN_NAME);
        public static final UniqueKey<RoleRecord> AK_ROLE_EE_NAME = createUniqueKey(Role.ROLE, "ak_role_ee_name", Role.ROLE.EE_NAME);
        public static final UniqueKey<ThesisRecord> PK_THESIS_THESIS_ID = createUniqueKey(Thesis.THESIS, "pk_thesis_thesis_id", Thesis.THESIS.THESIS_ID);
        public static final UniqueKey<ThesisCandidateRecord> PK_THESIS_CANDIDATE_THESIS_ID_CANDIDATE_ID = createUniqueKey(ThesisCandidate.THESIS_CANDIDATE, "pk_thesis_candidate_thesis_id_candidate_id", ThesisCandidate.THESIS_CANDIDATE.THESIS_ID, ThesisCandidate.THESIS_CANDIDATE.CANDIDATE_ID);
        public static final UniqueKey<ThesisOwnerRecord> PK_THESIS_OWNER_THESIS_ID_PERSON_ID = createUniqueKey(ThesisOwner.THESIS_OWNER, "pk_thesis_owner_thesis_id_person_id", ThesisOwner.THESIS_OWNER.THESIS_ID, ThesisOwner.THESIS_OWNER.PERSON_ID);
        public static final UniqueKey<ThesisStateRecord> PK_THESIS_STATE_THESIS_STATE_CODE = createUniqueKey(ThesisState.THESIS_STATE, "pk_thesis_state_thesis_state_code", ThesisState.THESIS_STATE.THESIS_STATE_CODE);
        public static final UniqueKey<ThesisStateRecord> AK_THESIS_STATE_EE_NAME = createUniqueKey(ThesisState.THESIS_STATE, "ak_thesis_state_ee_name", ThesisState.THESIS_STATE.EE_NAME);
        public static final UniqueKey<ThesisStateRecord> AK_THESIS_STATE_EN_NAME = createUniqueKey(ThesisState.THESIS_STATE, "ak_thesis_state_en_name", ThesisState.THESIS_STATE.EN_NAME);
        public static final UniqueKey<ThesisTagRecord> PK_THESIS_TAG_THESIS_ID_TAG_NAME = createUniqueKey(ThesisTag.THESIS_TAG, "pk_thesis_tag_thesis_id_tag_name", ThesisTag.THESIS_TAG.THESIS_ID, ThesisTag.THESIS_TAG.TAG_NAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<PersonRecord, DegreeRecord> PERSON__FK_PERSON_DEGREE_CODE = createForeignKey(ee.ttu.unomomento.db.Keys.PK_DEGREE_DEGREE_CODE, Person.PERSON, "person__fk_person_degree_code", Person.PERSON.DEGREE_CODE);
        public static final ForeignKey<PersonRecord, PersonStateRecord> PERSON__FK_PERSON_PERSON_STATE_CODE = createForeignKey(ee.ttu.unomomento.db.Keys.PK_PERSON_STATE_PERSON_STATE_CODE, Person.PERSON, "person__fk_person_person_state_code", Person.PERSON.PERSON_STATE_CODE);
        public static final ForeignKey<PersonFacultyRecord, PersonRecord> PERSON_FACULTY__FK_PERSON_FACULTY_PERSON_ID = createForeignKey(ee.ttu.unomomento.db.Keys.PK_PERSON_PERSON_ID, PersonFaculty.PERSON_FACULTY, "person_faculty__fk_person_faculty_person_id", PersonFaculty.PERSON_FACULTY.PERSON_ID);
        public static final ForeignKey<PersonFacultyRecord, FacultyRecord> PERSON_FACULTY__FK_PERSON_FACULTY_FACULTY_CODE = createForeignKey(ee.ttu.unomomento.db.Keys.PK_FACULTY_FACULTY_CODE, PersonFaculty.PERSON_FACULTY, "person_faculty__fk_person_faculty_faculty_code", PersonFaculty.PERSON_FACULTY.FACULTY_CODE);
        public static final ForeignKey<PersonRoleRecord, PersonRecord> PERSON_ROLE__FK_PERSON_ROLE_PERSON_ID = createForeignKey(ee.ttu.unomomento.db.Keys.PK_PERSON_PERSON_ID, PersonRole.PERSON_ROLE, "person_role__fk_person_role_person_id", PersonRole.PERSON_ROLE.PERSON_ID);
        public static final ForeignKey<PersonRoleRecord, RoleRecord> PERSON_ROLE__FK_PERSON_ROLE_ROLE_CODE = createForeignKey(ee.ttu.unomomento.db.Keys.PK_ROLE_PERSON_ROLE_CODE, PersonRole.PERSON_ROLE, "person_role__fk_person_role_role_code", PersonRole.PERSON_ROLE.ROLE_CODE);
        public static final ForeignKey<ThesisRecord, FacultyRecord> THESIS__FK_THESIS_FACULTY_CODE = createForeignKey(ee.ttu.unomomento.db.Keys.PK_FACULTY_FACULTY_CODE, Thesis.THESIS, "thesis__fk_thesis_faculty_code", Thesis.THESIS.FACULTY_CODE);
        public static final ForeignKey<ThesisRecord, ThesisStateRecord> THESIS__FK_THESIS_THESIS_STATE_CODE = createForeignKey(ee.ttu.unomomento.db.Keys.PK_THESIS_STATE_THESIS_STATE_CODE, Thesis.THESIS, "thesis__fk_thesis_thesis_state_code", Thesis.THESIS.THESIS_STATE_CODE);
        public static final ForeignKey<ThesisCandidateRecord, ThesisRecord> THESIS_CANDIDATE__FK_THESIS_CANDIDATE_THESIS_ID = createForeignKey(ee.ttu.unomomento.db.Keys.PK_THESIS_THESIS_ID, ThesisCandidate.THESIS_CANDIDATE, "thesis_candidate__fk_thesis_candidate_thesis_id", ThesisCandidate.THESIS_CANDIDATE.THESIS_ID);
        public static final ForeignKey<ThesisCandidateRecord, PersonRecord> THESIS_CANDIDATE__FK_THESIS_CANDIDATE_CANDIDATE_ID = createForeignKey(ee.ttu.unomomento.db.Keys.PK_PERSON_PERSON_ID, ThesisCandidate.THESIS_CANDIDATE, "thesis_candidate__fk_thesis_candidate_candidate_id", ThesisCandidate.THESIS_CANDIDATE.CANDIDATE_ID);
        public static final ForeignKey<ThesisOwnerRecord, ThesisRecord> THESIS_OWNER__FK_THESIS_OWNER_THESIS_ID = createForeignKey(ee.ttu.unomomento.db.Keys.PK_THESIS_THESIS_ID, ThesisOwner.THESIS_OWNER, "thesis_owner__fk_thesis_owner_thesis_id", ThesisOwner.THESIS_OWNER.THESIS_ID);
        public static final ForeignKey<ThesisOwnerRecord, PersonRecord> THESIS_OWNER__FK_THESIS_OWNER_PERSON_ID = createForeignKey(ee.ttu.unomomento.db.Keys.PK_PERSON_PERSON_ID, ThesisOwner.THESIS_OWNER, "thesis_owner__fk_thesis_owner_person_id", ThesisOwner.THESIS_OWNER.PERSON_ID);
        public static final ForeignKey<ThesisOwnerRecord, RoleRecord> THESIS_OWNER__FK_THESIS_OWNER_ROLE_CODE = createForeignKey(ee.ttu.unomomento.db.Keys.PK_ROLE_PERSON_ROLE_CODE, ThesisOwner.THESIS_OWNER, "thesis_owner__fk_thesis_owner_role_code", ThesisOwner.THESIS_OWNER.ROLE_CODE);
        public static final ForeignKey<ThesisTagRecord, ThesisRecord> THESIS_TAG__FK_THESIS_TAG_THESIS_ID = createForeignKey(ee.ttu.unomomento.db.Keys.PK_THESIS_THESIS_ID, ThesisTag.THESIS_TAG, "thesis_tag__fk_thesis_tag_thesis_id", ThesisTag.THESIS_TAG.THESIS_ID);
    }
}
