/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.Degree;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 1 -- No Degree, 2 -- Bachelor, 3 -- Master, 4 -- Doctoral, 5 -- Applied 
 * Higher Education
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DegreeRecord extends UpdatableRecordImpl<DegreeRecord> implements Record3<Short, String, String> {

    private static final long serialVersionUID = 841020258;

    /**
     * Setter for <code>public.degree.degree_code</code>.
     */
    public DegreeRecord setDegreeCode(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.degree.degree_code</code>.
     */
    public Short getDegreeCode() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.degree.ee_name</code>.
     */
    public DegreeRecord setEeName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.degree.ee_name</code>.
     */
    public String getEeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.degree.en_name</code>.
     */
    public DegreeRecord setEnName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.degree.en_name</code>.
     */
    public String getEnName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return Degree.DEGREE.DEGREE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Degree.DEGREE.EE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Degree.DEGREE.EN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getDegreeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEnName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DegreeRecord value1(Short value) {
        setDegreeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DegreeRecord value2(String value) {
        setEeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DegreeRecord value3(String value) {
        setEnName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DegreeRecord values(Short value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DegreeRecord
     */
    public DegreeRecord() {
        super(Degree.DEGREE);
    }

    /**
     * Create a detached, initialised DegreeRecord
     */
    public DegreeRecord(Short degreeCode, String eeName, String enName) {
        super(Degree.DEGREE);

        set(0, degreeCode);
        set(1, eeName);
        set(2, enName);
    }
}
