/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonState implements Serializable {

    private static final long serialVersionUID = -1341328599;

    private final Short  personStateCode;
    private final String eeName;
    private final String enName;

    public PersonState(PersonState value) {
        this.personStateCode = value.personStateCode;
        this.eeName = value.eeName;
        this.enName = value.enName;
    }

    public PersonState(
        Short  personStateCode,
        String eeName,
        String enName
    ) {
        this.personStateCode = personStateCode;
        this.eeName = eeName;
        this.enName = enName;
    }

    public Short getPersonStateCode() {
        return this.personStateCode;
    }

    public String getEeName() {
        return this.eeName;
    }

    public String getEnName() {
        return this.enName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PersonState (");

        sb.append(personStateCode);
        sb.append(", ").append(eeName);
        sb.append(", ").append(enName);

        sb.append(")");
        return sb.toString();
    }
}
