/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisOwner implements Serializable {

    private static final long serialVersionUID = -2114724816;

    private final Long  thesisId;
    private final Long  personId;
    private final Short roleCode;

    public ThesisOwner(ThesisOwner value) {
        this.thesisId = value.thesisId;
        this.personId = value.personId;
        this.roleCode = value.roleCode;
    }

    public ThesisOwner(
        Long  thesisId,
        Long  personId,
        Short roleCode
    ) {
        this.thesisId = thesisId;
        this.personId = personId;
        this.roleCode = roleCode;
    }

    public Long getThesisId() {
        return this.thesisId;
    }

    public Long getPersonId() {
        return this.personId;
    }

    public Short getRoleCode() {
        return this.roleCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ThesisOwner (");

        sb.append(thesisId);
        sb.append(", ").append(personId);
        sb.append(", ").append(roleCode);

        sb.append(")");
        return sb.toString();
    }
}
