/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.domains;


import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
// ((btrim((VALUE)::text) <> ''::text) AND ((VALUE)::text !~ '^[[:digit:]]+$'::text))
public class DName {
}
