/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.AccountState;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountStateRecord extends UpdatableRecordImpl<AccountStateRecord> implements Record3<Short, String, String> {

    private static final long serialVersionUID = 1755475401;

    /**
     * Setter for <code>public.account_state.account_state_code</code>.
     */
    public AccountStateRecord setAccountStateCode(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.account_state.account_state_code</code>.
     */
    public Short getAccountStateCode() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.account_state.ee_name</code>.
     */
    public AccountStateRecord setEeName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.account_state.ee_name</code>.
     */
    public String getEeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account_state.en_name</code>.
     */
    public AccountStateRecord setEnName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.account_state.en_name</code>.
     */
    public String getEnName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return AccountState.ACCOUNT_STATE.ACCOUNT_STATE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AccountState.ACCOUNT_STATE.EE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AccountState.ACCOUNT_STATE.EN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getAccountStateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEnName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountStateRecord value1(Short value) {
        setAccountStateCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountStateRecord value2(String value) {
        setEeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountStateRecord value3(String value) {
        setEnName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountStateRecord values(Short value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountStateRecord
     */
    public AccountStateRecord() {
        super(AccountState.ACCOUNT_STATE);
    }

    /**
     * Create a detached, initialised AccountStateRecord
     */
    public AccountStateRecord(Short accountStateCode, String eeName, String enName) {
        super(AccountState.ACCOUNT_STATE);

        set(0, accountStateCode);
        set(1, eeName);
        set(2, enName);
    }
}
