/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.CuratorsWithTheses;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CuratorsWithThesesRecord extends TableRecordImpl<CuratorsWithThesesRecord> implements Record7<Long, String, Short, String, String, Short, Object> {

    private static final long serialVersionUID = -578263929;

    /**
     * Setter for <code>public.curators_with_theses.person_id</code>.
     */
    public CuratorsWithThesesRecord setPersonId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.curators_with_theses.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.curators_with_theses.uni_id</code>.
     */
    public CuratorsWithThesesRecord setUniId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.curators_with_theses.uni_id</code>.
     */
    public String getUniId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.curators_with_theses.degree_code</code>.
     */
    public CuratorsWithThesesRecord setDegreeCode(Short value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.curators_with_theses.degree_code</code>.
     */
    public Short getDegreeCode() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.curators_with_theses.firstname</code>.
     */
    public CuratorsWithThesesRecord setFirstname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.curators_with_theses.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.curators_with_theses.lastname</code>.
     */
    public CuratorsWithThesesRecord setLastname(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.curators_with_theses.lastname</code>.
     */
    public String getLastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.curators_with_theses.person_state_code</code>.
     */
    public CuratorsWithThesesRecord setPersonStateCode(Short value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.curators_with_theses.person_state_code</code>.
     */
    public Short getPersonStateCode() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.curators_with_theses.theses</code>.
     */
    public CuratorsWithThesesRecord setTheses(Object value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.curators_with_theses.theses</code>.
     */
    public Object getTheses() {
        return (Object) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Short, String, String, Short, Object> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Short, String, String, Short, Object> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CuratorsWithTheses.CURATORS_WITH_THESES.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CuratorsWithTheses.CURATORS_WITH_THESES.UNI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return CuratorsWithTheses.CURATORS_WITH_THESES.DEGREE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CuratorsWithTheses.CURATORS_WITH_THESES.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CuratorsWithTheses.CURATORS_WITH_THESES.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return CuratorsWithTheses.CURATORS_WITH_THESES.PERSON_STATE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field7() {
        return CuratorsWithTheses.CURATORS_WITH_THESES.THESES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUniId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getDegreeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getPersonStateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value7() {
        return getTheses();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord value1(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord value2(String value) {
        setUniId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord value3(Short value) {
        setDegreeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord value4(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord value5(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord value6(Short value) {
        setPersonStateCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord value7(Object value) {
        setTheses(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuratorsWithThesesRecord values(Long value1, String value2, Short value3, String value4, String value5, Short value6, Object value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CuratorsWithThesesRecord
     */
    public CuratorsWithThesesRecord() {
        super(CuratorsWithTheses.CURATORS_WITH_THESES);
    }

    /**
     * Create a detached, initialised CuratorsWithThesesRecord
     */
    public CuratorsWithThesesRecord(Long personId, String uniId, Short degreeCode, String firstname, String lastname, Short personStateCode, Object theses) {
        super(CuratorsWithTheses.CURATORS_WITH_THESES);

        set(0, personId);
        set(1, uniId);
        set(2, degreeCode);
        set(3, firstname);
        set(4, lastname);
        set(5, personStateCode);
        set(6, theses);
    }
}
