/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.PersonFaculty;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonFacultyRecord extends UpdatableRecordImpl<PersonFacultyRecord> implements Record2<Long, Short> {

    private static final long serialVersionUID = -247643696;

    /**
     * Setter for <code>public.person_faculty.person_id</code>.
     */
    public PersonFacultyRecord setPersonId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.person_faculty.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.person_faculty.faculty_code</code>.
     */
    public PersonFacultyRecord setFacultyCode(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.person_faculty.faculty_code</code>.
     */
    public Short getFacultyCode() {
        return (Short) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Short> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Short> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PersonFaculty.PERSON_FACULTY.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return PersonFaculty.PERSON_FACULTY.FACULTY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getFacultyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonFacultyRecord value1(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonFacultyRecord value2(Short value) {
        setFacultyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonFacultyRecord values(Long value1, Short value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonFacultyRecord
     */
    public PersonFacultyRecord() {
        super(PersonFaculty.PERSON_FACULTY);
    }

    /**
     * Create a detached, initialised PersonFacultyRecord
     */
    public PersonFacultyRecord(Long personId, Short facultyCode) {
        super(PersonFaculty.PERSON_FACULTY);

        set(0, personId);
        set(1, facultyCode);
    }
}
