/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.Role;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 1 -- Student, 2 -- Curator
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> implements Record3<Short, String, String> {

    private static final long serialVersionUID = -864185078;

    /**
     * Setter for <code>public.role.role_code</code>.
     */
    public RoleRecord setRoleCode(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.role.role_code</code>.
     */
    public Short getRoleCode() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.role.en_name</code>.
     */
    public RoleRecord setEnName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.role.en_name</code>.
     */
    public String getEnName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.role.ee_name</code>.
     */
    public RoleRecord setEeName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.role.ee_name</code>.
     */
    public String getEeName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return Role.ROLE.ROLE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Role.ROLE.EN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Role.ROLE.EE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getRoleCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEnName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleRecord value1(Short value) {
        setRoleCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleRecord value2(String value) {
        setEnName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleRecord value3(String value) {
        setEeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleRecord values(Short value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(Short roleCode, String enName, String eeName) {
        super(Role.ROLE);

        set(0, roleCode);
        set(1, enName);
        set(2, eeName);
    }
}
