/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.ThesisPicked;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisPickedRecord extends UpdatableRecordImpl<ThesisPickedRecord> implements Record3<Long, Long, Short> {

    private static final long serialVersionUID = -1106975835;

    /**
     * Setter for <code>public.thesis_picked.thesis_id</code>.
     */
    public ThesisPickedRecord setThesisId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_picked.thesis_id</code>.
     */
    public Long getThesisId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.thesis_picked.person_id</code>.
     */
    public ThesisPickedRecord setPersonId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_picked.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.thesis_picked.degree_code</code>.
     */
    public ThesisPickedRecord setDegreeCode(Short value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_picked.degree_code</code>.
     */
    public Short getDegreeCode() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Short> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Short> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ThesisPicked.THESIS_PICKED.THESIS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ThesisPicked.THESIS_PICKED.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return ThesisPicked.THESIS_PICKED.DEGREE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getThesisId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getDegreeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisPickedRecord value1(Long value) {
        setThesisId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisPickedRecord value2(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisPickedRecord value3(Short value) {
        setDegreeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisPickedRecord values(Long value1, Long value2, Short value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThesisPickedRecord
     */
    public ThesisPickedRecord() {
        super(ThesisPicked.THESIS_PICKED);
    }

    /**
     * Create a detached, initialised ThesisPickedRecord
     */
    public ThesisPickedRecord(Long thesisId, Long personId, Short degreeCode) {
        super(ThesisPicked.THESIS_PICKED);

        set(0, thesisId);
        set(1, personId);
        set(2, degreeCode);
    }
}
