/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.ThesisTag;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisTagRecord extends UpdatableRecordImpl<ThesisTagRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -913991107;

    /**
     * Setter for <code>public.thesis_tag.thesis_id</code>.
     */
    public ThesisTagRecord setThesisId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_tag.thesis_id</code>.
     */
    public Long getThesisId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.thesis_tag.tag_name</code>.
     */
    public ThesisTagRecord setTagName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_tag.tag_name</code>.
     */
    public String getTagName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ThesisTag.THESIS_TAG.THESIS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ThesisTag.THESIS_TAG.TAG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getThesisId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTagName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisTagRecord value1(Long value) {
        setThesisId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisTagRecord value2(String value) {
        setTagName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisTagRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThesisTagRecord
     */
    public ThesisTagRecord() {
        super(ThesisTag.THESIS_TAG);
    }

    /**
     * Create a detached, initialised ThesisTagRecord
     */
    public ThesisTagRecord(Long thesisId, String tagName) {
        super(ThesisTag.THESIS_TAG);

        set(0, thesisId);
        set(1, tagName);
    }
}
