/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.records;


import ee.ttu.unomomento.db.tables.ThesisState;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 1 -- Active, 2 - Inactive, 3 - Reserved
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisStateRecord extends UpdatableRecordImpl<ThesisStateRecord> implements Record3<Short, String, String> {

    private static final long serialVersionUID = -1629250660;

    /**
     * Setter for <code>public.thesis_state.thesis_state_code</code>.
     */
    public ThesisStateRecord setThesisStateCode(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_state.thesis_state_code</code>.
     */
    public Short getThesisStateCode() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.thesis_state.ee_name</code>.
     */
    public ThesisStateRecord setEeName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_state.ee_name</code>.
     */
    public String getEeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.thesis_state.en_name</code>.
     */
    public ThesisStateRecord setEnName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.thesis_state.en_name</code>.
     */
    public String getEnName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Short, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return ThesisState.THESIS_STATE.THESIS_STATE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ThesisState.THESIS_STATE.EE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ThesisState.THESIS_STATE.EN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getThesisStateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEnName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisStateRecord value1(Short value) {
        setThesisStateCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisStateRecord value2(String value) {
        setEeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisStateRecord value3(String value) {
        setEnName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisStateRecord values(Short value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThesisStateRecord
     */
    public ThesisStateRecord() {
        super(ThesisState.THESIS_STATE);
    }

    /**
     * Create a detached, initialised ThesisStateRecord
     */
    public ThesisStateRecord(Short thesisStateCode, String eeName, String enName) {
        super(ThesisState.THESIS_STATE);

        set(0, thesisStateCode);
        set(1, eeName);
        set(2, enName);
    }
}
