/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables;


import ee.ttu.unomomento.db.Keys;
import ee.ttu.unomomento.db.Public;
import ee.ttu.unomomento.db.tables.records.PersonFacultyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonFaculty extends TableImpl<PersonFacultyRecord> {

    private static final long serialVersionUID = 809768141;

    /**
     * The reference instance of <code>public.person_faculty</code>
     */
    public static final PersonFaculty PERSON_FACULTY = new PersonFaculty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersonFacultyRecord> getRecordType() {
        return PersonFacultyRecord.class;
    }

    /**
     * The column <code>public.person_faculty.person_id</code>.
     */
    public final TableField<PersonFacultyRecord, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.person_faculty.faculty_code</code>.
     */
    public final TableField<PersonFacultyRecord, Short> FACULTY_CODE = createField("faculty_code", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * Create a <code>public.person_faculty</code> table reference
     */
    public PersonFaculty() {
        this("person_faculty", null);
    }

    /**
     * Create an aliased <code>public.person_faculty</code> table reference
     */
    public PersonFaculty(String alias) {
        this(alias, PERSON_FACULTY);
    }

    private PersonFaculty(String alias, Table<PersonFacultyRecord> aliased) {
        this(alias, aliased, null);
    }

    private PersonFaculty(String alias, Table<PersonFacultyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersonFacultyRecord> getPrimaryKey() {
        return Keys.PK_PERSON_FACULTY_PERSON_ID_FACULTY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersonFacultyRecord>> getKeys() {
        return Arrays.<UniqueKey<PersonFacultyRecord>>asList(Keys.PK_PERSON_FACULTY_PERSON_ID_FACULTY_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PersonFacultyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PersonFacultyRecord, ?>>asList(Keys.PERSON_FACULTY__FK_PERSON_FACULTY_PERSON_ID, Keys.PERSON_FACULTY__FK_PERSON_FACULTY_FACULTY_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonFaculty as(String alias) {
        return new PersonFaculty(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PersonFaculty rename(String name) {
        return new PersonFaculty(name, null);
    }
}
