/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables;


import ee.ttu.unomomento.db.Keys;
import ee.ttu.unomomento.db.Public;
import ee.ttu.unomomento.db.tables.records.ThesisTagRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisTag extends TableImpl<ThesisTagRecord> {

    private static final long serialVersionUID = 1851910816;

    /**
     * The reference instance of <code>public.thesis_tag</code>
     */
    public static final ThesisTag THESIS_TAG = new ThesisTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThesisTagRecord> getRecordType() {
        return ThesisTagRecord.class;
    }

    /**
     * The column <code>public.thesis_tag.thesis_id</code>.
     */
    public final TableField<ThesisTagRecord, Long> THESIS_ID = createField("thesis_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.thesis_tag.tag_name</code>.
     */
    public final TableField<ThesisTagRecord, String> TAG_NAME = createField("tag_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * Create a <code>public.thesis_tag</code> table reference
     */
    public ThesisTag() {
        this("thesis_tag", null);
    }

    /**
     * Create an aliased <code>public.thesis_tag</code> table reference
     */
    public ThesisTag(String alias) {
        this(alias, THESIS_TAG);
    }

    private ThesisTag(String alias, Table<ThesisTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private ThesisTag(String alias, Table<ThesisTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ThesisTagRecord> getPrimaryKey() {
        return Keys.PK_THESIS_TAG_THESIS_ID_TAG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ThesisTagRecord>> getKeys() {
        return Arrays.<UniqueKey<ThesisTagRecord>>asList(Keys.PK_THESIS_TAG_THESIS_ID_TAG_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ThesisTagRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ThesisTagRecord, ?>>asList(Keys.THESIS_TAG__FK_THESIS_TAG_THESIS_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisTag as(String alias) {
        return new ThesisTag(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ThesisTag rename(String name) {
        return new ThesisTag(name, null);
    }
}
