/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables;


import ee.ttu.unomomento.db.Keys;
import ee.ttu.unomomento.db.Public;
import ee.ttu.unomomento.db.tables.records.ThesisCandidateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisCandidate extends TableImpl<ThesisCandidateRecord> {

    private static final long serialVersionUID = 1858150468;

    /**
     * The reference instance of <code>public.thesis_candidate</code>
     */
    public static final ThesisCandidate THESIS_CANDIDATE = new ThesisCandidate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThesisCandidateRecord> getRecordType() {
        return ThesisCandidateRecord.class;
    }

    /**
     * The column <code>public.thesis_candidate.thesis_id</code>.
     */
    public final TableField<ThesisCandidateRecord, Long> THESIS_ID = createField("thesis_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.thesis_candidate.candidate_id</code>.
     */
    public final TableField<ThesisCandidateRecord, Long> CANDIDATE_ID = createField("candidate_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.thesis_candidate</code> table reference
     */
    public ThesisCandidate() {
        this("thesis_candidate", null);
    }

    /**
     * Create an aliased <code>public.thesis_candidate</code> table reference
     */
    public ThesisCandidate(String alias) {
        this(alias, THESIS_CANDIDATE);
    }

    private ThesisCandidate(String alias, Table<ThesisCandidateRecord> aliased) {
        this(alias, aliased, null);
    }

    private ThesisCandidate(String alias, Table<ThesisCandidateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ThesisCandidateRecord> getPrimaryKey() {
        return Keys.PK_THESIS_CANDIDATE_THESIS_ID_CANDIDATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ThesisCandidateRecord>> getKeys() {
        return Arrays.<UniqueKey<ThesisCandidateRecord>>asList(Keys.PK_THESIS_CANDIDATE_THESIS_ID_CANDIDATE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ThesisCandidateRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ThesisCandidateRecord, ?>>asList(Keys.THESIS_CANDIDATE__FK_THESIS_CANDIDATE_THESIS_ID, Keys.THESIS_CANDIDATE__FK_THESIS_CANDIDATE_CANDIDATE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThesisCandidate as(String alias) {
        return new ThesisCandidate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ThesisCandidate rename(String name) {
        return new ThesisCandidate(name, null);
    }
}
