/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.account_account_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_ACCOUNT_ID_SEQ = new SequenceImpl<Long>("account_account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.person_person_id_seq</code>
     */
    public static final Sequence<Long> PERSON_PERSON_ID_SEQ = new SequenceImpl<Long>("person_person_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.thesis_thesis_id_seq</code>
     */
    public static final Sequence<Long> THESIS_THESIS_ID_SEQ = new SequenceImpl<Long>("thesis_thesis_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
