/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db;


import ee.ttu.unomomento.db.tables.Account;
import ee.ttu.unomomento.db.tables.AccountRole;
import ee.ttu.unomomento.db.tables.AccountState;
import ee.ttu.unomomento.db.tables.Degree;
import ee.ttu.unomomento.db.tables.Faculty;
import ee.ttu.unomomento.db.tables.Person;
import ee.ttu.unomomento.db.tables.PersonFaculty;
import ee.ttu.unomomento.db.tables.PersonRole;
import ee.ttu.unomomento.db.tables.Role;
import ee.ttu.unomomento.db.tables.Thesis;
import ee.ttu.unomomento.db.tables.ThesisCandidate;
import ee.ttu.unomomento.db.tables.ThesisOwner;
import ee.ttu.unomomento.db.tables.ThesisState;
import ee.ttu.unomomento.db.tables.ThesisTag;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = ee.ttu.unomomento.db.tables.Account.ACCOUNT;

    /**
     * The table <code>public.account_role</code>.
     */
    public static final AccountRole ACCOUNT_ROLE = ee.ttu.unomomento.db.tables.AccountRole.ACCOUNT_ROLE;

    /**
     * The table <code>public.account_state</code>.
     */
    public static final AccountState ACCOUNT_STATE = ee.ttu.unomomento.db.tables.AccountState.ACCOUNT_STATE;

    /**
     * 1 -- No Degree, 2 -- Bachelor, 3 -- Master, 4 -- Doctoral, 5 -- Applied Higher Education
     */
    public static final Degree DEGREE = ee.ttu.unomomento.db.tables.Degree.DEGREE;

    /**
     * 1 -- School of Business and Governance, 2 -- School of Engineering, 3 -- School of Information Technologies, 4 -- School of Science, 5 -- Estonian Maritime Academy
     */
    public static final Faculty FACULTY = ee.ttu.unomomento.db.tables.Faculty.FACULTY;

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = ee.ttu.unomomento.db.tables.Person.PERSON;

    /**
     * The table <code>public.person_faculty</code>.
     */
    public static final PersonFaculty PERSON_FACULTY = ee.ttu.unomomento.db.tables.PersonFaculty.PERSON_FACULTY;

    /**
     * The table <code>public.person_role</code>.
     */
    public static final PersonRole PERSON_ROLE = ee.ttu.unomomento.db.tables.PersonRole.PERSON_ROLE;

    /**
     * 1 -- Student, 2 -- Curator
     */
    public static final Role ROLE = ee.ttu.unomomento.db.tables.Role.ROLE;

    /**
     * The table <code>public.thesis</code>.
     */
    public static final Thesis THESIS = ee.ttu.unomomento.db.tables.Thesis.THESIS;

    /**
     * The table <code>public.thesis_candidate</code>.
     */
    public static final ThesisCandidate THESIS_CANDIDATE = ee.ttu.unomomento.db.tables.ThesisCandidate.THESIS_CANDIDATE;

    /**
     * The table <code>public.thesis_owner</code>.
     */
    public static final ThesisOwner THESIS_OWNER = ee.ttu.unomomento.db.tables.ThesisOwner.THESIS_OWNER;

    /**
     * 1 -- Active, 2 - Inactive, 3 - Reserved
     */
    public static final ThesisState THESIS_STATE = ee.ttu.unomomento.db.tables.ThesisState.THESIS_STATE;

    /**
     * The table <code>public.thesis_tag</code>.
     */
    public static final ThesisTag THESIS_TAG = ee.ttu.unomomento.db.tables.ThesisTag.THESIS_TAG;
}
