/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountState implements Serializable {

    private static final long serialVersionUID = 974498131;

    private final Short  accountStateCode;
    private final String eeName;
    private final String enName;

    public AccountState(AccountState value) {
        this.accountStateCode = value.accountStateCode;
        this.eeName = value.eeName;
        this.enName = value.enName;
    }

    public AccountState(
        Short  accountStateCode,
        String eeName,
        String enName
    ) {
        this.accountStateCode = accountStateCode;
        this.eeName = eeName;
        this.enName = enName;
    }

    public Short getAccountStateCode() {
        return this.accountStateCode;
    }

    public String getEeName() {
        return this.eeName;
    }

    public String getEnName() {
        return this.enName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountState (");

        sb.append(accountStateCode);
        sb.append(", ").append(eeName);
        sb.append(", ").append(enName);

        sb.append(")");
        return sb.toString();
    }
}
