/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRole implements Serializable {

    private static final long serialVersionUID = -1169984096;

    private final Short  accountRoleCode;
    private final String roleName;

    public AccountRole(AccountRole value) {
        this.accountRoleCode = value.accountRoleCode;
        this.roleName = value.roleName;
    }

    public AccountRole(
        Short  accountRoleCode,
        String roleName
    ) {
        this.accountRoleCode = accountRoleCode;
        this.roleName = roleName;
    }

    public Short getAccountRoleCode() {
        return this.accountRoleCode;
    }

    public String getRoleName() {
        return this.roleName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountRole (");

        sb.append(accountRoleCode);
        sb.append(", ").append(roleName);

        sb.append(")");
        return sb.toString();
    }
}
