/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@NoArgsConstructor
@Setter
public class Account implements Serializable {

    private static final long serialVersionUID = 1091301464;

    private Long      accountId;
    private String    username;
    private String    password;
    private String    email;
    private Short     accountStateCode;
    private Short     accountRoleCode;
    private Timestamp regTime;

    public Account(Account value) {
        this.accountId = value.accountId;
        this.username = value.username;
        this.password = value.password;
        this.email = value.email;
        this.accountStateCode = value.accountStateCode;
        this.accountRoleCode = value.accountRoleCode;
        this.regTime = value.regTime;
    }

    public Account(
        Long      accountId,
        String    username,
        String    password,
        String    email,
        Short     accountStateCode,
        Short     accountRoleCode,
        Timestamp regTime
    ) {
        this.accountId = accountId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.accountStateCode = accountStateCode;
        this.accountRoleCode = accountRoleCode;
        this.regTime = regTime;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public String getUsername() {
        return this.username;
    }

    public String getPassword() {
        return this.password;
    }

    public String getEmail() {
        return this.email;
    }

    public Short getAccountStateCode() {
        return this.accountStateCode;
    }

    public Short getAccountRoleCode() {
        return this.accountRoleCode;
    }

    public Timestamp getRegTime() {
        return this.regTime;
    }

    public void setPassword(String value) {
        this.password = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(accountId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(accountStateCode);
        sb.append(", ").append(accountRoleCode);
        sb.append(", ").append(regTime);

        sb.append(")");
        return sb.toString();
    }
}
