/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CuratorsWithTheses implements Serializable {

    private static final long serialVersionUID = -1929484667;

    private final Long   personId;
    private final String uniId;
    private final Short  degreeCode;
    private final String firstname;
    private final String lastname;
    private final Short  personStateCode;
    private final Object theses;

    public CuratorsWithTheses(CuratorsWithTheses value) {
        this.personId = value.personId;
        this.uniId = value.uniId;
        this.degreeCode = value.degreeCode;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.personStateCode = value.personStateCode;
        this.theses = value.theses;
    }

    public CuratorsWithTheses(
        Long   personId,
        String uniId,
        Short  degreeCode,
        String firstname,
        String lastname,
        Short  personStateCode,
        Object theses
    ) {
        this.personId = personId;
        this.uniId = uniId;
        this.degreeCode = degreeCode;
        this.firstname = firstname;
        this.lastname = lastname;
        this.personStateCode = personStateCode;
        this.theses = theses;
    }

    public Long getPersonId() {
        return this.personId;
    }

    public String getUniId() {
        return this.uniId;
    }

    public Short getDegreeCode() {
        return this.degreeCode;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public Short getPersonStateCode() {
        return this.personStateCode;
    }

    public Object getTheses() {
        return this.theses;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CuratorsWithTheses (");

        sb.append(personId);
        sb.append(", ").append(uniId);
        sb.append(", ").append(degreeCode);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(personStateCode);
        sb.append(", ").append(theses);

        sb.append(")");
        return sb.toString();
    }
}
