/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 1 -- No Degree, 2 -- Bachelor, 3 -- Master, 4 -- Doctoral, 5 -- Applied 
 * Higher Education
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Degree implements Serializable {

    private static final long serialVersionUID = -2096127454;

    private final Short  degreeCode;
    private final String eeName;
    private final String enName;

    public Degree(Degree value) {
        this.degreeCode = value.degreeCode;
        this.eeName = value.eeName;
        this.enName = value.enName;
    }

    public Degree(
        Short  degreeCode,
        String eeName,
        String enName
    ) {
        this.degreeCode = degreeCode;
        this.eeName = eeName;
        this.enName = enName;
    }

    public Short getDegreeCode() {
        return this.degreeCode;
    }

    public String getEeName() {
        return this.eeName;
    }

    public String getEnName() {
        return this.enName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Degree (");

        sb.append(degreeCode);
        sb.append(", ").append(eeName);
        sb.append(", ").append(enName);

        sb.append(")");
        return sb.toString();
    }
}
