/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonFaculty implements Serializable {

    private static final long serialVersionUID = 659100559;

    private final Long  personId;
    private final Short facultyCode;

    public PersonFaculty(PersonFaculty value) {
        this.personId = value.personId;
        this.facultyCode = value.facultyCode;
    }

    public PersonFaculty(
        Long  personId,
        Short facultyCode
    ) {
        this.personId = personId;
        this.facultyCode = facultyCode;
    }

    public Long getPersonId() {
        return this.personId;
    }

    public Short getFacultyCode() {
        return this.facultyCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PersonFaculty (");

        sb.append(personId);
        sb.append(", ").append(facultyCode);

        sb.append(")");
        return sb.toString();
    }
}
