/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 1 -- Active, 2 - Inactive, 3 - Reserved
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisState implements Serializable {

    private static final long serialVersionUID = 269551175;

    private final Short  thesisStateCode;
    private final String eeName;
    private final String enName;

    public ThesisState(ThesisState value) {
        this.thesisStateCode = value.thesisStateCode;
        this.eeName = value.eeName;
        this.enName = value.enName;
    }

    public ThesisState(
        Short  thesisStateCode,
        String eeName,
        String enName
    ) {
        this.thesisStateCode = thesisStateCode;
        this.eeName = eeName;
        this.enName = enName;
    }

    public Short getThesisStateCode() {
        return this.thesisStateCode;
    }

    public String getEeName() {
        return this.eeName;
    }

    public String getEnName() {
        return this.enName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ThesisState (");

        sb.append(thesisStateCode);
        sb.append(", ").append(eeName);
        sb.append(", ").append(enName);

        sb.append(")");
        return sb.toString();
    }
}
