/*
 * This file is generated by jOOQ.
*/
package ee.ttu.unomomento.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThesisCandidate implements Serializable {

    private static final long serialVersionUID = -1018279891;

    private final Long thesisId;
    private final Long candidateId;

    public ThesisCandidate(ThesisCandidate value) {
        this.thesisId = value.thesisId;
        this.candidateId = value.candidateId;
    }

    public ThesisCandidate(
        Long thesisId,
        Long candidateId
    ) {
        this.thesisId = thesisId;
        this.candidateId = candidateId;
    }

    public Long getThesisId() {
        return this.thesisId;
    }

    public Long getCandidateId() {
        return this.candidateId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ThesisCandidate (");

        sb.append(thesisId);
        sb.append(", ").append(candidateId);

        sb.append(")");
        return sb.toString();
    }
}
